apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-moose
spec:
  selector:
    matchLabels:
      app: animals-moose
  replicas: 1
  template: 
    metadata:
      labels:
        app: animals-moose
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-bear
spec:
  selector:
    matchLabels:
      app: animals-bear
  replicas: 1 
  template: 
    metadata:
      labels:
        app: animals-bear
    spec:
      containers:
      - name: animals
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bear-svc
spec:
  selector:
    app: animals-bear
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 100.64.171.241
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: moose-svc
spec:
  selector:
    app: animals-moose
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 100.64.171.242
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: animals-ingress
spec:
  ingressClassName: ingress-nginx-controller
  rules:
  - http:
      paths:
      - path: /moose
        pathType: Prefix
        backend:
          service:
            name: moose-svc
            port:
              number: 80
      - path: /bear
        pathType: Prefix
        backend:
          service:
            name: bear-svc
            port:
              number: 80