apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-deployment
spec:
  selector:
    matchLabels:
      app: svc
  replicas: 2 
  template: 
    metadata:
      labels:
        app: svc
    spec:
      containers:
      - name: yanivomc
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: 100.64.171.239
  type: LoadBalancer
