database: 
  dbname: db_mysql
  dbtable: music
database-test: 
  dbname: db_mysql-test
  dbtable: music
pods: 
  image: yanivomc/spring-music
drink: beer
eat: Peanut Butter and Jelly sandwich
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
deployment:
  replicas: 2
  image: yanivomc/spring-music:latest
